FROM node:20 as base

FROM base AS play
WORKDIR /code
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
RUN npx playwright install --with-deps

FROM play AS build
COPY . .
RUN npm run build
CMD ["npx", "playwright", "test"]