// src/app/api/missing-persons/route.ts
export async function GET() {
  return Response.json([
    {
      case_id: "MP137407",
      date_missing: "01/17/2025",
      last_name: "Moneta",
      first_name: "Jeremiah",
      age: "22",
      missing_city: "Ponca City",
      missing_county: "Kay",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Black / African American",
      date_modified: "01/29/2025",
    },
    {
      case_id: "MP136447",
      date_missing: "01/12/2025",
      last_name: "Chalepah",
      first_name: "Allen",
      age: "14",
      missing_city: "Anadarko",
      missing_county: "McClain",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "American Indian / Alaska Native",
      date_modified: "01/22/2025",
    },
    {
      case_id: "MP136016",
      date_missing: "01/05/2025",
      last_name: "Nicole",
      first_name: "Twitty",
      age: "17",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Female",
      race_ethnicity: "Black / African American",
      date_modified: "01/22/2025",
    },
    {
      case_id: "MP135785",
      date_missing: "12/31/2024",
      last_name: "Marmolejo",
      first_name: "Isabella",
      age: "19",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Female",
      race_ethnicity: "Hispanic / Latino, White / Caucasian",
      date_modified: "01/06/2025",
    },
    {
      case_id: "MP136266",
      date_missing: "12/19/2024",
      last_name: "Reyes - Luviano",
      first_name: "Juan",
      age: "40",
      missing_city: "Tulsa",
      missing_county: "Tulsa",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Hispanic / Latino",
      date_modified: "01/17/2025",
    },
    {
      case_id: "MP137360",
      date_missing: "12/13/2024",
      last_name: "Orton",
      first_name: "Kenneth",
      age: "52",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "01/28/2025",
    },
    {
      case_id: "MP137356",
      date_missing: "12/11/2024",
      last_name: "Stevenson Jr",
      first_name: "Edward",
      age: "33",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Black / African American",
      date_modified: "01/28/2025",
    },
    {
      case_id: "MP134817",
      date_missing: "12/08/2024",
      last_name: "Smith",
      first_name: "Zachary",
      age: "48",
      missing_city: "Sand Springs",
      missing_county: "Osage",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/16/2024",
    },
    {
      case_id: "MP136437",
      date_missing: "12/07/2024",
      last_name: "Rousch",
      first_name: "Ralph",
      age: "62",
      missing_city: "Tulsa",
      missing_county: "Tulsa",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "01/13/2025",
    },
    {
      case_id: "MP135979",
      date_missing: "12/07/2024",
      last_name: "Sherman",
      first_name: "William",
      age: "63",
      missing_city: "Tulsa",
      missing_county: "Tulsa",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Black / African American",
      date_modified: "01/06/2025",
    },
    {
      case_id: "MP137436",
      date_missing: "11/28/2024",
      last_name: "Ontiveros",
      first_name: "Joshua",
      age: "47",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "01/29/2025",
    },
    {
      case_id: "MP133993",
      date_missing: "11/26/2024",
      last_name: "Thomas",
      first_name: "Rochelle",
      age: "59",
      missing_city: "Thackerville",
      missing_county: "Love",
      missing_state: "OK",
      sex: "Female",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/17/2024",
    },
    {
      case_id: "MP134854",
      date_missing: "11/24/2024",
      last_name: "Little",
      first_name: "Matthew",
      age: "15",
      missing_city: "Lawton",
      missing_county: "Comanche",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/16/2024",
    },
    {
      case_id: "MP135268",
      date_missing: "11/20/2024",
      last_name: "Ray",
      first_name: "Joshua",
      age: "15",
      missing_city: "Norman",
      missing_county: "Cleveland",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Uncertain",
      date_modified: "12/23/2024",
    },
    {
      case_id: "MP134177",
      date_missing: "11/20/2024",
      last_name: "Knox",
      first_name: "Josiah",
      age: "14",
      missing_city: "Lawton",
      missing_county: "Comanche",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Black / African American",
      date_modified: "12/13/2024",
    },
    {
      case_id: "MP137348",
      date_missing: "11/18/2024",
      last_name: "Mapp",
      first_name: "Raylene",
      age: "23",
      missing_city: "Oklahoma City",
      missing_county: "Oklahoma",
      missing_state: "OK",
      sex: "Female",
      race_ethnicity: "Black / African American",
      date_modified: "01/28/2025",
    },
    {
      case_id: "MP134597",
      date_missing: "11/16/2024",
      last_name: "Dupre",
      first_name: "David",
      age: "54",
      missing_city: "Duncan",
      missing_county: "Stephens",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "01/30/2025",
    },
    {
      case_id: "MP135265",
      date_missing: "11/15/2024",
      last_name: "Starks",
      first_name: "Isiah",
      age: "16",
      missing_city: "Norman",
      missing_county: "Cleveland",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Black / African American",
      date_modified: "12/23/2024",
    },
    {
      case_id: "MP135264",
      date_missing: "11/13/2024",
      last_name: "Zepeta",
      first_name: "Mario",
      age: "16",
      missing_city: "Norman",
      missing_county: "Cleveland",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "Uncertain",
      date_modified: "12/23/2024",
    },
    {
      case_id: "MP134345",
      date_missing: "11/11/2024",
      last_name: "Redmond",
      first_name: "Christopher",
      age: "54",
      missing_city: "Muskogee",
      missing_county: "Muskogee",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/13/2024",
    },
    {
      case_id: "MP133841",
      date_missing: "11/08/2024",
      last_name: "Dickerson",
      first_name: "Donaven",
      age: "24",
      missing_city: "Broken Arrow",
      missing_county: "Wagoner",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian, American Indian / Alaska Native",
      date_modified: "12/02/2024",
    },
    {
      case_id: "MP135262",
      date_missing: "11/07/2024",
      last_name: "Carlson",
      first_name: "Brandon",
      age: "19",
      missing_city: "Norman",
      missing_county: "Cleveland",
      missing_state: "OK",
      sex: "Male",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/23/2024",
    },
    {
      case_id: "MP135063",
      date_missing: "10/31/2024",
      last_name: "Torres",
      first_name: "Jazlyn",
      age: "17",
      missing_city: "Enid",
      missing_county: "Garfield",
      missing_state: "OK",
      sex: "Female",
      race_ethnicity: "White / Caucasian",
      date_modified: "12/18/2024",
    },
  ]);
}
