import { MissingPerson } from "@/table/page";

// Mock data for requests
export const mockRequests: MissingPerson[] = [
  {
    case_id: "MP112231",
    first_name: "John",
    last_name: "Doe",
    age: "32",
    gender: "Male",
    race: "White",
    missing_date: new Date("2025-04-01"),
    city: "Portland",
    county: "Multnomah",
    date_modified: new Date("2025-04-05"),
    tribes: ["N/A"],
    tribe_statuses: ["N/A"],
    classification: "Endangered Missing",
    category_of_missing: "Adult",
  },
  {
    case_id: "MP112232",
    first_name: "Maria",
    last_name: "Garcia",
    age: "17",
    gender: "Female",
    race: "Hispanic",
    missing_date: new Date("2025-03-28"),
    city: "Salem",
    county: "Marion",
    date_modified: new Date("2025-04-03"),
    tribes: ["N/A"],
    tribe_statuses: ["N/A"],
    classification: "Missing Juvenile",
    category_of_missing: "Juvenile",
  },
  {
    case_id: "MP112233",
    first_name: "Robert",
    last_name: "Smith",
    age: "45",
    gender: "Male",
    race: "Native American",
    missing_date: new Date("2025-03-30"),
    city: "Warm Springs",
    county: "Jefferson",
    date_modified: new Date("2025-04-02"),
    tribes: ["Choctaw Nation"],
    tribe_statuses: ["Enrolled"],
    classification: "Endangered Missing",
    category_of_missing: "Adult",
  },
  {
    case_id: "MP112234",
    first_name: "Sarah",
    last_name: "Johnson",
    age: "26",
    gender: "Female",
    race: "Black",
    missing_date: new Date("2025-04-05"),
    city: "Eugene",
    county: "Lane",
    date_modified: new Date("2025-04-07"),
    tribes: ["N/A"],
    tribe_statuses: ["N/A"],
    classification: "Missing Adult",
    category_of_missing: "Adult",
  },
];
